//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThienNguyen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietUngHo
    {
        public string MaCTUH { get; set; }
        public string TenHoatDong { get; set; }
        public string MaDVUH { get; set; }
        public string MaDUH { get; set; }
        public string MaHD { get; set; }
        public string MaHTUH { get; set; }
        public Nullable<double> SoLuongUH { get; set; }
        public Nullable<double> SoLuongNUH { get; set; }
        public string MoTa { get; set; }
        public byte[] AnhHoatDong { get; set; }
    
        public virtual DotUngHo DotUngHo { get; set; }
        public virtual DonViUngHo DonViUngHo { get; set; }
        public virtual HinhThucUngHo HinhThucUngHo { get; set; }
        public virtual HoDan HoDan { get; set; }
    }
}
