//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThienNguyen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViUngHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViUngHo()
        {
            this.ChiTietUngHos = new HashSet<ChiTietUngHo>();
            this.ThanhVienDVUHs = new HashSet<ThanhVienDVUH>();
            this.ThongKes = new HashSet<ThongKe>();
        }
    
        public string MaDVUH { get; set; }
        public string TenDonVi { get; set; }
        public string DiaChiDonVi { get; set; }
        public string SDTDonVi { get; set; }

        public DonViUngHo(string id, string name, string address, string sdt)
        {
            MaDVUH = id;
            TenDonVi = name;
            DiaChiDonVi = address;
            SDTDonVi = sdt;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietUngHo> ChiTietUngHos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhVienDVUH> ThanhVienDVUHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKe> ThongKes { get; set; }
    }
}
