//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThienNguyen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVienDVUH
    {
        public string MaTVDVUH { get; set; }
        public string MaDVUH { get; set; }
        public string HoTen { get; set; }
        public bool GioiTinh { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public ThanhVienDVUH(string ma, string ten, bool gt, string cccd, string dc, string sdt)
        {
            this.MaDVUH = ma;
            this.HoTen = ten;
            this.GioiTinh = gt;
            this.CCCD = cccd;
            this.DiaChi = dc;
            this.SDT = sdt;
        }

        public virtual DonViUngHo DonViUngHo { get; set; }
    }
}
